[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -std=gnu++17
    
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320

    -D USE_HSPI_PORT=1
    -D TFT_SPI_READ_FREQUENCY=0
    -D SPI_FREQUENCY=20000000
    
    -D SPI_DRIVER_SELECT=2

    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_DC=9
    -D TFT_CS=10
    -D TFT_RST=14
    -D TFT_MISO=3
    -D TFT_BL=41

    -D SPI_READ_FREQUENCY=20000000
    
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1

build_unflags =
    -std=gnu++11
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0

upload_port = COM3
monitor_port = COM3
monitor_speed = 115200

lib_ldf_mode = deep+

